### ISSUE TITLE
'Clamp'  option in interpolation & overshootClamping

### ISSUE THREAD

**Issue by gregonarash** [stefanwittwer/remotion-animated#1]
Hey @stefanwittwer ,

Great library and serious chunk of work! I am just looking into incorporating your way of handling Remotion animations into may project.

I was looking into Move and the animation  was having almost zero bounce. The  overshootClamping was set to `false` , so the  spring value was overshooting the range as it supposed to but the object was not moving.  Digging through code I realized that the `interpolate`  has hardcoded "clamp",  which  will prevent any bounce.  Was that intended?

https://github.com/stefanwittwer/remotion-animated/blob/6d18ffbc00e66344d51178e4176b3c69a053f953/packages/remotion-animated/src/animations/AnimationInterpolation.ts#L15

I removed the `ClampInterpolationOptions` and it works fine. Maybe solution would be to have that removed as default and add  on overshootClamping set to `true` ?

Thanks you!

**Comment by stefanwittwer** [comment]
Hi there!
Thank you so much for raising the issue.

This library is mostly an extraction from some helper code I wrote to help me build an animation faster. 
For that animation, I wanted a super-quick way to get spring animations that looked a certain way, which did not involve any bounce. So it was added intentionally because of this.

However, I totally see the need to make this more flexible, now that others are using the library for their own use cases. Thanks for bringing it up!

My goal is for the "default out-of-the-box animation style" (which deliberately prevents bounce) to remain consistent between versions. I like your suggestion to achieve this by setting `overshootClamping` instead on the default `SmoothSpring` config, as this can be overriden when using the library.

I'll try it out and publish an update if it works.

**Comment by stefanwittwer** [comment]
This change is now included in version 1.0.3 of the package. Thanks again!

**Comment by gregonarash** [comment]
Hey @stefanwittwer!

This works greats! Big kudos again, as this way of adding animations, makes it really scalable to add multiple animations. 

Thanks, I will share my project soon, connecting Remotion to ... Airtable...

**Comment by stefanwittwer** [comment]
Awesome to hear, and thank you for the kind words🙏🏻 Excited to see what you're building
